/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lock.h"


void
locksvc_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	callback_args register_cb_1_arg1;
	enum clnt_stat retval_2;
	hash_resp result_2;
	hash_args get_hashes_1_arg1;
	enum clnt_stat retval_3;
	int result_3;
	fname put_hashes_1_name;
	hash_resp put_hashes_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, locksvc, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = register_cb_1(register_cb_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = get_hashes_1(get_hashes_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = put_hashes_1(put_hashes_1_name, put_hashes_1_arg2, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	locksvc_1 (host);
exit (0);
}
