/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "lock.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
register_cb_1(callback_args arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, register_cb,
		(xdrproc_t) xdr_callback_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_hashes_1(hash_args arg1, hash_resp *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_hashes,
		(xdrproc_t) xdr_hash_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_hash_resp, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
put_hashes_1(fname name, hash_resp arg2, int *clnt_res,  CLIENT *clnt)
{
	put_hashes_1_argument arg;
	arg.name = name;
	arg.arg2 = arg2;
	return (clnt_call (clnt, put_hashes, (xdrproc_t) xdr_put_hashes_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
