/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lock.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_register_cb_1 (callback_args  *argp, void *result, struct svc_req *rqstp)
{
	return (register_cb_1_svc(*argp, result, rqstp));
}

int
_get_hashes_1 (hash_args  *argp, void *result, struct svc_req *rqstp)
{
	return (get_hashes_1_svc(*argp, result, rqstp));
}

int
_put_hashes_1 (put_hashes_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (put_hashes_1_svc(argp->name, argp->arg2, result, rqstp));
}

static void
locksvc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		callback_args register_cb_1_arg;
		hash_args get_hashes_1_arg;
		put_hashes_1_argument put_hashes_1_arg;
	} argument;
	union {
		int register_cb_1_res;
		hash_resp get_hashes_1_res;
		int put_hashes_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case register_cb:
		_xdr_argument = (xdrproc_t) xdr_callback_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_register_cb_1;
		break;

	case get_hashes:
		_xdr_argument = (xdrproc_t) xdr_hash_args;
		_xdr_result = (xdrproc_t) xdr_hash_resp;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_get_hashes_1;
		break;

	case put_hashes:
		_xdr_argument = (xdrproc_t) xdr_put_hashes_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_put_hashes_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!locksvc_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (locksvc, v1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, locksvc, v1, locksvc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (locksvc, v1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, locksvc, v1, locksvc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (locksvc, v1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
