/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lock.h"

bool_t
xdr_fname (XDR *xdrs, fname *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_callback_args (XDR *xdrs, callback_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->proto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hash_args (XDR *xdrs, hash_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cbid))
		 return FALSE;
	 if (!xdr_fname (xdrs, &objp->name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hash (XDR *xdrs, hash *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, HASHLENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hash_res (XDR *xdrs, hash_res *objp)
{
	register int32_t *buf;

	 if (!xdr_hash (xdrs, &objp->digest))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hash_resp (XDR *xdrs, hash_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->hash_resp_val, (u_int *) &objp->hash_resp_len, MAXHASHES,
		sizeof (hash_res), (xdrproc_t) xdr_hash_res))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_put_hashes_1_argument (XDR *xdrs, put_hashes_1_argument *objp)
{
	 if (!xdr_fname (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_hash_resp (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
